spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/atsd
spring.datasource.username=${POSTGRES_USER:atsd}
spring.datasource.password=${POSTGRES_PASSWORD:atsd}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect