name: Developer Tests

on: push

jobs:
  launch-tests:
    runs-on: ubuntu-latest
    container: openjdk:21-ea-1-jdk

    steps:
      - uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Launch tests with Maven
        run: ./mvnw test
